### ISSUE TITLE
Can we run the action for all commit in a PR instead of the latest commit?

### ISSUE THREAD

**Issue by weizhangfd** [webiny/action-conventional-commits#8]
Hello,

Thank you for the super useful action! We have integrated it as the required status check in github before PR merge. One thing we have note is that each time someone pushes to an open PR, the action only runs on the latest pushed commit. So if the latest commit conforms conventional commit while some older commit messages not conforming, the required status check still passed and the PR can be merged. It's only after merged, the action is triggered again on main branch, that we receive an error that some older message isn't conforming.

Is there a way to run the action on all commits of a PR?

Thanks!

**Comment by JossWhittle** [comment]
@weizhangfd did you ever find a solution to this?

**Comment by pallabpain** [comment]
Hitting the same issue with one of my repos. Albeit, it seems to work on a test repo that I created for the purpose of testing the action. I have a `main` branch and `dev` branch my action looks something like this
```yaml
name: Check Commit Hygiene 💬

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  verify:
    name: Conventional Commits
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - uses: webiny/action-conventional-commits@v1.1.0
      name: Check if commit messages are compliant
```

**Comment by lyager** [comment]
@pallabpain So, a PR from dev->main triggers an error if the commit messages are not convetional? My setup looks somewhat similar - but the error triggers on the main branch, when it's too late.

**Comment by pallabpain** [comment]
> @pallabpain So, a PR from dev->main triggers an error if the commit messages are not convetional? My setup looks somewhat similar - but the error triggers on the main branch, when it's too late.

You can take a look at this test repo that I created: https://github.com/pallabpain/conventional-commits-action

The main doesn't yet have the `.github/workflows` directory yet. Only `devel` has it and I raised a `pull_request` against `devel`. (https://github.com/pallabpain/conventional-commits-action/pull/1) and the action is detecting the commits. 

However, with another repository with a similar branch structure, it's not detecting the commits.

**Comment by JobaDiniz** [comment]
It's not working for me, and I get this _warning_:
>Warning: Unexpected input(s) 'GITHUB_TOKEN', valid inputs are ['']

```yml
name: commit

on:
  pull_request:
    branches: [ develop ]

jobs:
  commits:
    name: check commit message
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check message commit message
      uses: webiny/action-conventional-commits@v1.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  label:
    needs: commits
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
```
